export const ItemNames = {
  Aircraft: [
    'You don’t have an Aircraft yet',
    'Paper airplane',
    'Alien spaceship',
    'Pogo stick',
    'Rocket',
    'Cardboard airplane',
    'Fighter jet',
    'Large jet',
    'Lawn chair balloons',
    'Trampoline',
    'Toy drone',
    'Medium jet',
    'Cannon',
    'Large helicopter',
    'Hot air balloon',
    'Personal drone',
    'Big propeller plane',
    'Small jet',
    'Biplane',
    'Small helicopter',
    'Small propeller plane',
  ],
  Character: [
    'You don’t have a Character yet',
    'Tracksuit',
    'Royalty',
    'Lumberjack',
    'Tycoon',
    'Disco suit',
    'Capitalist',
    'Artist',
    'Ski outfit',
    'Judge',
    'Football player',
    'Scientist',
    'Marching band',
    'Pilot',
    'Chef',
    'Mailman',
    'Farmer',
    'Police officer',
    'Military',
    'Firefighter',
    'Doctor',
  ],
  Vehicle: [
    'You don’t have a Vehicle yet',
    'Shopping cart',
    'Supercar',
    'Tank',
    'Skateboard',
    'Limo',
    'Fancy sedan',
    'Scooter',
    'Junk car',
    'Unicycle',
    'Vintage sports car',
    'Riding lawn mower',
    'SUV',
    'Horse',
    'Super compact car',
    'Motorcycle',
    'Van',
    'Kids tricycle',
    'Bicycle',
    'Sedan',
    'Coupe',
  ],
  House: [
    'You don’t have a House yet',
    'Carboard box',
    'Palace',
    'Dumpster',
    'Luxury villa',
    'Castle',
    'Sand castle',
    'Mansion',
    'Igloo',
    'Bounce house',
    'Tent',
    'Shipping container',
    'Tree house',
    'Haunted house',
    'Luxury condo',
    'Hobbit hole',
    'Beach house',
    'Mobile home',
    'Cheap apartment',
    'Condo',
    'Single family home',
  ],
  Boat: [
    'You don’t have a Boat yet',
    'Life jacket',
    'Aircraft carrier',
    'Unicorn float',
    'Super yacht',
    'Inner tube',
    'Submarine',
    'Log raft',
    'Cargo ship',
    'Surf board',
    'Large motor boat',
    'Canoe',
    'Kayak',
    'Pirate ship',
    'Row boat',
    'Paddle boat',
    'Small sailboat',
    'Small motor boat',
    'Medium sailboat',
    'Medium motor boat',
    'Yacht',
  ],
}
